03-19 22:50:45 jdbc[5]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.test(WebApp.java:845)
	at org.h2.server.web.WebApp.process(WebApp.java:219)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 14 more
03-21 00:15:22 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT * FROM TBL_PLAYERS 


SELECT[*] MARKETTYPE FROM TBL_PLAYERS WHERE TRADESUBJECTID=''"; SQL statement:
SELECT * FROM TBL_PLAYERS 


SELECT MARKETTYPE FROM TBL_PLAYERS WHERE TRADESUBJECTID='' [42000-175]
03-26 23:20:29 jdbc[5]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 14 more
03-30 01:27:58 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DROP FROM[*] TBL_FORMULA "; expected "TABLE, INDEX, USER, SEQUENCE, CONSTANT, TRIGGER, VIEW, ROLE, ALIAS, SCHEMA, ALL, DOMAIN, TYPE, DATATYPE, AGGREGATE"; SQL statement:
drop FROM TBL_FORMULA [42001-175]
03-30 01:28:03 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DROP  TBL_FORMULA[*] "; expected "TABLE, INDEX, USER, SEQUENCE, CONSTANT, TRIGGER, VIEW, ROLE, ALIAS, SCHEMA, ALL, DOMAIN, TYPE, DATATYPE, AGGREGATE"; SQL statement:
drop  TBL_FORMULA [42001-175]
03-30 01:28:05 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DROP  TBL_FORMULA[*] "; expected "TABLE, INDEX, USER, SEQUENCE, CONSTANT, TRIGGER, VIEW, ROLE, ALIAS, SCHEMA, ALL, DOMAIN, TYPE, DATATYPE, AGGREGATE"; SQL statement:
drop  TBL_FORMULA [42001-175]
03-30 01:28:17 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DROP TBL_FORMULA[*] "; expected "TABLE, INDEX, USER, SEQUENCE, CONSTANT, TRIGGER, VIEW, ROLE, ALIAS, SCHEMA, ALL, DOMAIN, TYPE, DATATYPE, AGGREGATE"; SQL statement:
drop TBL_FORMULA [42001-175]
03-30 01:28:26 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DROP FROM[*] TBL_FORMULA "; expected "TABLE, INDEX, USER, SEQUENCE, CONSTANT, TRIGGER, VIEW, ROLE, ALIAS, SCHEMA, ALL, DOMAIN, TYPE, DATATYPE, AGGREGATE"; SQL statement:
drop from TBL_FORMULA [42001-175]
03-30 01:28:40 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DROP *[*] TBL_FORMULA "; expected "TABLE, INDEX, USER, SEQUENCE, CONSTANT, TRIGGER, VIEW, ROLE, ALIAS, SCHEMA, ALL, DOMAIN, TYPE, DATATYPE, AGGREGATE"; SQL statement:
drop * TBL_FORMULA [42001-175]
04-20 12:21:32 jdbc[110]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "CREATE TABLE TBL_HEAD (ID BIGINT AUTO_INCREMENT, FEEDSECID VARCHAR(255) NOT NUL[*], SYMBOL VARCHAR(255) NOT NULL, LOTSIZE VARCHAR(255) NULL, TICKSIZE VARCHAR(255) NULL, EXCHANGE VARCHAR(255) NULL, INSTTYPE VARCHAR(255) NULL, EXPIRYDATE VARCHAR(255) NULL
, EXPIRYMMMYY VARCHAR (255) NULL,  OPTTYPE VARCHAR(255) NULL, STRIKEPRICE VARCHAR(255) NULL) "; expected "NULL"; SQL statement:
create table tbl_Head (id bigint auto_increment, feedsecid varchar(255) not nul, symbol varchar(255) not null, lotsize varchar(255) null, ticksize varchar(255) null, exchange varchar(255) null, insttype varchar(255) null, expirydate varchar(255) null
, expirymmmyy varchar (255) null,  opttype varchar(255) null, strikeprice varchar(255) null) [42001-175]
04-20 12:28:12 jdbc[110]: exception
org.h2.jdbc.JdbcSQLException: Table "TBL_PLAYERS" already exists; SQL statement:
create table tbl_players (id bigint auto_increment, feedsecid varchar(255) not null, playersecid varchar(255) not null, symbol varchar(255) not null, lotsize varchar(255) null, ticksize varchar(255) null, exchange varchar(255) null, insttype varchar(255) null, expirydate varchar(255) null, expirymmmyy varchar (255) null,  opttype varchar(255) null, strikeprice varchar(255) null) [42101-175]
04-20 15:44:34 jdbc[112]: exception
org.h2.jdbc.JdbcSQLException: Table "TBL_TRADERS" already exists; SQL statement:
create table tbl_traders (id bigint auto_increment, feedsecid varchar(255) not null, playersecid varchar(255) not null, symbol varchar(255) not null, lotsize varchar(255) null, ticksize varchar(255) null, exchange varchar(255) null, insttype varchar(255) null, expirydd varchar(255) null, expirymmmyy varchar (255) null,  opttype varchar(255) null, strikeprice varchar(255) null) [42101-175]
04-20 16:29:11 jdbc[115]: exception
org.h2.jdbc.JdbcSQLException: Table "TBL_HEADS" not found; SQL statement:
INSERT INTO TBL_HEADS (FEEDSECID,SYMBOL,LOTSIZE,TICKSIZE,EXCHANGE,INSTTYPE,EXPIRYDD,EXPIRYMMMYY,OPTTYPE,STRIKEPRICE) VALUES ('INFY','INFY','INFY','INFY','INFY','INFY','INFY','INFY','INFY','INFY') [42102-175]
04-23 15:16:15 jdbc[44]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 14 more
04-23 16:40:20 jdbc[45]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 14 more
04-23 17:07:51 jdbc[45]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DELETE *[*] FROM TBL_TRADERS"; expected "identifier"; SQL statement:
DELETE * FROM TBL_TRADERS [42001-175]
04-23 17:07:51 jdbc[45]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DELETE *[*] FROM TBL_HEAD"; expected "identifier"; SQL statement:
DELETE * FROM TBL_HEAD [42001-175]
04-23 17:07:51 jdbc[45]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DELETE *[*] FROM TBL_TRADEBOARD"; expected "identifier"; SQL statement:
DELETE * FROM TBL_TRADEBOARD [42001-175]
04-23 19:43:53 jdbc[124]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 14 more
04-23 21:15:23 jdbc[132]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DROP FROM[*] TBL_HEADFEEDS"; expected "TABLE, INDEX, USER, SEQUENCE, CONSTANT, TRIGGER, VIEW, ROLE, ALIAS, SCHEMA, ALL, DOMAIN, TYPE, DATATYPE, AGGREGATE"; SQL statement:
DROP FROM TBL_HEADFEEDS [42001-175]
04-23 22:17:08 jdbc[133]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 14 more
04-23 23:16:41 jdbc[133]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DELETE *[*] FROM TBL_TRADEBOARD"; expected "identifier"; SQL statement:
DELETE * FROM TBL_TRADEBOARD [42001-175]
04-23 23:44:20 jdbc[133]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "TBL_F1_HRUN_TRADES"; expected "TRUNCATE, {"; SQL statement:
TBL_F1_HRUN_TRADES [42001-175]
04-24 00:31:27 jdbc[133]: exception
org.h2.jdbc.JdbcSQLException: Table "TBL_F3_HRUN_TRADES" already exists; SQL statement:
CREATE TABLE tbl_F3_HRun_TRADES (ID bigint auto_increment, FEEDSECID varchar(255) null, TRADESECID  varchar(255) not null, ENTRYTIME  varchar(255) null, BUYPRICE double null,
SELLPRICE double null, EXITTIME varchar(255) null, ISSHOTSELL varchar(255) null, HIGH double null, LOW double null, ISBOUGHT varchar(255) null, ISSELL varchar(255) null, MPOINT double null, EXITCONDITION varchar(255) null, TCOUNT int null, isbuyselldone varchar(255) null, ENTRYID varchar(255) null, EXITID varchar(255) null, C int null, LC int null, S int null ) [42101-175]
04-25 10:19:17 jdbc[1397]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "UPDATE TBL_TRADEBOARD  SET  F1PL = NULL AND F1PC = NULL AND F1TC = NULL AND F2PL = NULL AND F2PC = NULL AND F2TC = NULL AND F1PC  = NULL AND 
F1PC = NULL AND  F3PL  = NULL AND F3PC = NULL AND F3TC = NULL AND F4PL = NULL AND  F4PC = NULL AND  F4TC = NULL AND F5PL = NULL AND F5PC = NULL AND  F5TC = NULL AND   F6PL = NULL AND F6PC = NULL AND  F6TC = NULL AND  F7PL = NULL AND F7PC = NULL AND 
F7TC = NULL AND WHERE[*] ID > 0 "; expected "NOT, EXISTS, INTERSECTS, SELECT, FROM"; SQL statement:
UPDATE TBL_TRADEBOARD  set  F1PL = null AND F1PC = null AND F1TC = null AND F2PL = null AND F2PC = null AND F2TC = null AND F1PC  = null AND 
F1PC = null AND  F3PL  = null AND F3PC = null AND F3TC = null AND F4PL = null AND  F4PC = null AND  F4TC = null AND F5PL = null AND F5PC = null AND  F5TC = null AND   F6PL = null AND F6PC = null AND  F6TC = null AND  F7PL = null AND F7PC = null AND 
F7TC = null AND WHERE ID > 0 [42001-175]
04-25 10:20:18 jdbc[1397]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "UPDATE TBL_TRADEBOARD  SET  F1PL = NULL AND F1PC = NULL AND F1TC = NULL AND F2PL = NULL AND F2PC = NULL AND F2TC = NULL AND F1PC  = NULL AND 
F1PC = NULL AND  F3PL  = NULL AND F3PC = NULL AND F3TC = NULL AND F4PL = NULL AND  F4PC = NULL AND  F4TC = NULL AND F5PL = NULL AND F5PC = NULL AND  F5TC = NULL AND   F6PL = NULL AND F6PC = NULL AND  F6TC = NULL AND  F7PL = NULL AND F7PC = NULL AND 
F7TC = NULL AND WHERE[*] ID > 0 "; expected "NOT, EXISTS, INTERSECTS, SELECT, FROM"; SQL statement:
UPDATE TBL_TRADEBOARD  set  F1PL = null AND F1PC = null AND F1TC = null AND F2PL = null AND F2PC = null AND F2TC = null AND F1PC  = null AND 
F1PC = null AND  F3PL  = null AND F3PC = null AND F3TC = null AND F4PL = null AND  F4PC = null AND  F4TC = null AND F5PL = null AND F5PC = null AND  F5TC = null AND   F6PL = null AND F6PC = null AND  F6TC = null AND  F7PL = null AND F7PC = null AND 
F7TC = null AND WHERE ID > 0 [42001-175]
04-25 12:36:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT * FROM TBL_FORMULA 


DELETE *[*] FROM  TBL_FORMULA  WHERE ID >42 "; SQL statement:
SELECT * FROM TBL_FORMULA 


Delete * from  TBL_FORMULA  where id >42 [42000-175]
04-25 13:24:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "UPDATE TBL_F1_HRUN_TRADES  SET ISSHOTSELL='true', ENTRYTIME='Wed Apr 25 13:20:39 IST 2018',SELLPRICE=10606.0, ,[*] ISSELL='true',TCOUNT=1, LOW =10606.0, HIGH=10609.45, MPOINT=10606.267165000001,C=0.0, LC=0.0, S=0.0 , WHERE FEEDSECID='50496' AND TRADESECID ='52380' AND ISBUYSELLDONE ='false' "; expected "identifier"; SQL statement:
UPDATE TBL_F1_HRUN_TRADES  SET ISSHOTSELL='true', ENTRYTIME='Wed Apr 25 13:20:39 IST 2018',SELLPRICE=10606.0, , isSell='true',Tcount=1, LOW =10606.0, HIGH=10609.45, Mpoint=10606.267165000001,C=0.0, LC=0.0, S=0.0 , WHERE FEEDSECID='50496' and TRADESECID ='52380' and ISBUYSELLDONE ='false' [42001-175]
04-25 13:26:07 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "UPDATE TBL_F1_HRUN_TRADES  SET ISSHOTSELL='true', ENTRYTIME='Wed Apr 25 13:20:39 IST 2018',SELLPRICE=10606.0, ,[*] ISSELL='true',TCOUNT=1, LOW =10606.0, HIGH=10609.45, MPOINT=10606.267165000001,C=0.0, LC=0.0, S=0.0 
WHERE FEEDSECID='50496' AND TRADESECID ='52380' AND ISBUYSELLDONE ='false' "; expected "identifier"; SQL statement:
UPDATE TBL_F1_HRUN_TRADES  SET ISSHOTSELL='true', ENTRYTIME='Wed Apr 25 13:20:39 IST 2018',SELLPRICE=10606.0, , isSell='true',Tcount=1, LOW =10606.0, HIGH=10609.45, Mpoint=10606.267165000001,C=0.0, LC=0.0, S=0.0 
WHERE FEEDSECID='50496' and TRADESECID ='52380' and ISBUYSELLDONE ='false' [42001-175]
04-25 14:11:01 jdbc[28586]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "UPDATE TBL_F1_HRUN_TRADES  SET ISSHOTSELL='true', ENTRYTIME='Wed Apr 25 13:20:39 IST 2018',SELLPRICE=10606.0, ,[*] ISSELL='true',TCOUNT=1, LOW =10606.0, HIGH=10609.45, MPOINT=10606.267165000001,C=0.0, LC=0.0, S=0.0 WHERE FEEDSECID='50496' AND TRADESECID ='52380' AND ISBUYSELLDONE ='false' "; expected "identifier"; SQL statement:
UPDATE TBL_F1_HRUN_TRADES  SET ISSHOTSELL='true', ENTRYTIME='Wed Apr 25 13:20:39 IST 2018',SELLPRICE=10606.0, , isSell='true',Tcount=1, LOW =10606.0, HIGH=10609.45, Mpoint=10606.267165000001,C=0.0, LC=0.0, S=0.0 WHERE FEEDSECID='50496' and TRADESECID ='52380' and ISBUYSELLDONE ='false' [42001-175]
04-25 14:32:14 jdbc[28586]: exception
org.h2.jdbc.JdbcSQLException: Duplicate column name "F1PC"; SQL statement:
UPDATE TBL_TRADEBOARD  set  F1PL = null ,F1PC = null ,F1TC = null ,F2PL = null ,F2PC = null ,F2TC = null ,F1PC  = null ,
F1PC = null ,F3PL  = null ,F3PC = null ,F3TC = null ,F4PL = null ,F4PC = null ,F4TC = null ,F5PL = null ,F5PC = null ,F5TC = null ,F6PL = null ,F6PC = null ,F6TC = null ,F7PL = null ,F7PC = null ,
F7TC = null  WHERE ID > 0 [42121-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.command.dml.Update.setAssignment(Update.java:69)
	at org.h2.command.Parser.parseUpdate(Parser.java:721)
	at org.h2.command.Parser.parsePrepared(Parser.java:448)
	at org.h2.command.Parser.parse(Parser.java:298)
	at org.h2.command.Parser.parse(Parser.java:270)
	at org.h2.command.Parser.prepareCommand(Parser.java:235)
	at org.h2.engine.Session.prepareLocal(Session.java:436)
	at org.h2.engine.Session.prepareCommand(Session.java:379)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:168)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:156)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1321)
	at org.h2.server.web.WebApp.query(WebApp.java:1010)
	at org.h2.server.web.WebApp$1.next(WebApp.java:972)
	at org.h2.server.web.WebApp$1.next(WebApp.java:959)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
04-25 14:39:06 jdbc[28586]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "UPDATE TBL_F1_HRUN_TRADES  SET ISSHOTSELL='true', ENTRYTIME='Wed Apr 25 14:37:39 IST 2018',SELLPRICE=10534.75, ISSELL='true',TCOUNT=1, LOW =10534.75, HIGH=10539.25, MPOINT=10536.088225,C=0.0, LC=0.0, S=0.0 , WHERE[*] FEEDSECID='50496' AND TRADESECID ='52380' AND ISBUYSELLDONE ='false' "; expected "identifier"; SQL statement:
UPDATE TBL_F1_HRUN_TRADES  SET ISSHOTSELL='true', ENTRYTIME='Wed Apr 25 14:37:39 IST 2018',SELLPRICE=10534.75, isSell='true',Tcount=1, LOW =10534.75, HIGH=10539.25, Mpoint=10536.088225,C=0.0, LC=0.0, S=0.0 , WHERE FEEDSECID='50496' and TRADESECID ='52380' and ISBUYSELLDONE ='false' [42001-175]
04-25 14:53:58 jdbc[28586]: exception
org.h2.jdbc.JdbcSQLException: Column "FEESECID" not found; SQL statement:
UPDATE TBL_FORMULA  SET ISEND='true' WHERE FEESECID='50496' AND TRADESECID='52380' AND FORMULANAME = 'F1' [42122-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:144)
	at org.h2.expression.Comparison.optimize(Comparison.java:177)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:131)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:131)
	at org.h2.command.dml.Update.prepare(Update.java:180)
	at org.h2.command.Parser.prepareCommand(Parser.java:240)
	at org.h2.engine.Session.prepareLocal(Session.java:436)
	at org.h2.engine.Session.prepareCommand(Session.java:379)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:168)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:156)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1321)
	at org.h2.server.web.WebApp.query(WebApp.java:1010)
	at org.h2.server.web.WebApp$1.next(WebApp.java:972)
	at org.h2.server.web.WebApp$1.next(WebApp.java:959)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
04-26 11:07:13 jdbc[60158]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ES[*]  WHERE FEEDSECID='50496' AND TRADESECID='52380' AND ISBUYSELLDONE =='true' "; expected "EXPLAIN, EXECUTE, {"; SQL statement:
ES  WHERE FEEDSECID='50496' and TRADESECID='52380' and ISBUYSELLDONE =='true' [42001-175]
04-26 13:15:20 jdbc[143695]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 14 more
04-26 13:15:20 jdbc[143695]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 14 more
04-26 13:44:27 jdbc[143695]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT * FROM TBL_FORMULA 


UPDATE TBL_FORMULA[*]  SET ISEND = FALSE WHERE ID =50 "; SQL statement:
SELECT * FROM TBL_FORMULA 


update TBL_FORMULA  set ISEND = false where id =50 [42000-175]
04-26 13:44:36 jdbc[143695]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT * FROM TBL_FORMULA 


UPDATE TBL_FORMULA[*]  SET ISEND = 'false' WHERE ID =50 "; SQL statement:
SELECT * FROM TBL_FORMULA 


update TBL_FORMULA  set ISEND = 'false' where id =50 [42000-175]
04-26 15:23:45 jdbc[183729]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 14 more
04-27 14:12:47 jdbc[323666]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 14 more
04-27 14:12:47 jdbc[323666]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 14 more
04-27 17:54:24 jdbc[406056]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 14 more
04-30 09:55:22 jdbc[406221]: exception
org.h2.jdbc.JdbcSQLException: Table "TBL_F2_HRUN_TRADES" not found; SQL statement:
DELETE FROM TBL_F2_HRUN_TRADES [42102-175]
04-30 09:55:22 jdbc[406221]: exception
org.h2.jdbc.JdbcSQLException: Table "TBL_F3_HRUN_TRADES" not found; SQL statement:
DELETE FROM  TBL_F3_HRUN_TRADES [42102-175]
04-30 09:55:22 jdbc[406221]: exception
org.h2.jdbc.JdbcSQLException: Table "TBL_F4_HCAPTURE_TRADES" not found; SQL statement:
DELETE FROM TBL_F4_HCAPTURE_TRADES [42102-175]
04-30 09:55:22 jdbc[406221]: exception
org.h2.jdbc.JdbcSQLException: Table "TBL_F5_HCAPTURE_TRADES" not found; SQL statement:
DELETE FROM TBL_F5_HCAPTURE_TRADES [42102-175]
04-30 09:55:22 jdbc[406221]: exception
org.h2.jdbc.JdbcSQLException: Table "TBL_F6_HCAPTURE_TRADES" not found; SQL statement:
DELETE FROM TBL_F6_HCAPTURE_TRADES [42102-175]
04-30 10:07:29 jdbc[406221]: exception
org.h2.jdbc.JdbcSQLException: Table "TBL_F2_HCAPTURE_TRADES" already exists; SQL statement:
CREATE TABLE tbl_F2_HCapture_TRADES (ID bigint auto_increment, FEEDSECID varchar(255) null, TRADESECID  varchar(255) not null, ENTRYTIME  varchar(255) null, BUYPRICE double null,
SELLPRICE double null, EXITTIME varchar(255) null, ISSHOTSELL varchar(255) null, HIGH double null, LOW double null, ISBOUGHT varchar(255) null, ISSELL varchar(255) null, MPOINT double null, EXITCONDITION varchar(255) null, TCOUNT int null, isbuyselldone varchar(255) null, ENTRYID varchar(255) null, EXITID varchar(255) null, C int null, LC int null, S int null ) [42101-175]
04-30 13:28:48 jdbc[492282]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 14 more
04-30 13:28:48 jdbc[492282]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 14 more
04-30 18:13:59 jdbc[558198]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 14 more
05-02 10:52:07 jdbc[558199]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DELETE *[*] FROM TBL_FORMULA  WHERE FEEDSECID='50138' "; expected "identifier"; SQL statement:
DELETE * FROM TBL_FORMULA  Where feedsecid='50138' [42001-175]
05-02 14:25:41 jdbc[720003]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 14 more
05-02 14:25:41 jdbc[720003]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 14 more
05-03 10:44:24 jdbc[784220]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 14 more
05-03 17:35:23 jdbc[993407]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 14 more
05-03 17:35:25 jdbc[993407]: exception
org.h2.jdbc.JdbcSQLException: Table "TBL_F2_HRUN_TRADES" not found; SQL statement:
SELECT FEEDSECID ,TRADESECID ,BUYPRICE ,SELLPRICE,ISSHOTSELL ,ENTRYTIME ,EXITTIME ,ENTRYID ,EXITID ,EXITCONDITION   FROM TBL_F2_HRUN_TRADES WHERE FEEDSECID = '3045' AND TRADESECID='3045' [42102-175]
05-04 11:48:18 jdbc[993500]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 14 more
05-04 11:48:18 jdbc[993500]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 14 more
05-04 11:48:30 jdbc[993500]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "UPDATE TBL_FORMULA SET ISEND  = 'false' WHERE FEEDSECID='3045'TBL_F2_HCAPTURE_TRADES[*] "; SQL statement:
update TBL_FORMULA set ISend  = 'false' where feedsecid='3045'TBL_F2_HCAPTURE_TRADES [42000-175]
05-04 12:20:46 jdbc[1011987]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 14 more
05-04 12:20:46 jdbc[1011987]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 14 more
05-04 12:56:11 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "13:00:00" not found; SQL statement:
UPDATE TBL_FORMULA set T1 ="13:00:00" where id >0 [42122-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:144)
	at org.h2.command.dml.Update.prepare(Update.java:187)
	at org.h2.command.Parser.prepareCommand(Parser.java:240)
	at org.h2.engine.Session.prepareLocal(Session.java:436)
	at org.h2.engine.Session.prepareCommand(Session.java:379)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:168)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:156)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1321)
	at org.h2.server.web.WebApp.query(WebApp.java:1010)
	at org.h2.server.web.WebApp$1.next(WebApp.java:972)
	at org.h2.server.web.WebApp$1.next(WebApp.java:959)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
05-04 12:56:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "13:00:00" not found; SQL statement:
UPDATE TBL_FORMULA set T1 ="13:00:00" where id > 0 [42122-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:144)
	at org.h2.command.dml.Update.prepare(Update.java:187)
	at org.h2.command.Parser.prepareCommand(Parser.java:240)
	at org.h2.engine.Session.prepareLocal(Session.java:436)
	at org.h2.engine.Session.prepareCommand(Session.java:379)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:168)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:156)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1321)
	at org.h2.server.web.WebApp.query(WebApp.java:1010)
	at org.h2.server.web.WebApp$1.next(WebApp.java:972)
	at org.h2.server.web.WebApp$1.next(WebApp.java:959)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
05-04 14:29:54 jdbc[18378]: exception
org.h2.jdbc.JdbcSQLException: Column "14:30:00" not found; SQL statement:
UPDATE TBL_FORMULA  SET T1 ="14:30:00"  WHERE ID >0 [42122-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:144)
	at org.h2.command.dml.Update.prepare(Update.java:187)
	at org.h2.command.Parser.prepareCommand(Parser.java:240)
	at org.h2.engine.Session.prepareLocal(Session.java:436)
	at org.h2.engine.Session.prepareCommand(Session.java:379)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:168)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:156)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1321)
	at org.h2.server.web.WebApp.query(WebApp.java:1010)
	at org.h2.server.web.WebApp$1.next(WebApp.java:972)
	at org.h2.server.web.WebApp$1.next(WebApp.java:959)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
05-04 14:30:04 jdbc[18378]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "UPDATE TBL_FORMULA  SET T1 =[*]'14:30:00.  WHERE ID >0"; SQL statement:
UPDATE TBL_FORMULA  SET T1 ='14:30:00.  WHERE ID >0 [42000-175]
05-07 09:45:43 jdbc[52500]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 14 more
05-07 11:26:53 jdbc[53230]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.test(WebApp.java:845)
	at org.h2.server.web.WebApp.process(WebApp.java:219)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 14 more
05-07 11:26:53 jdbc[53230]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.test(WebApp.java:845)
	at org.h2.server.web.WebApp.process(WebApp.java:219)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 14 more
05-07 11:26:53 jdbc[53230]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.test(WebApp.java:845)
	at org.h2.server.web.WebApp.process(WebApp.java:219)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 14 more
05-07 11:26:53 jdbc[53230]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.test(WebApp.java:845)
	at org.h2.server.web.WebApp.process(WebApp.java:219)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 14 more
05-07 14:35:45 jdbc[54529]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT CONCAT(FEEDSECID,'-',TSCRIB,'-',TRADESECID) AS SCRIB, F1PL AS[*] \""F1 P/L\"",F1PC AS \""F1 %\"", F1TC AS \""F1 COUNT\"" , F2PL AS \""F2 P/L\"",F2PC AS \""F2 %\"", F2TC AS \""F2 COUNT\""
, F3PL AS \""F3 P/L\"",F3PC AS \""F3 %\"", F3TC AS \""F3 COUNT\"" 
, F4PL AS \""F4 P/L\"",F4PC AS \""F4 %\"", F4TC AS \""F4 COUNT\"" 
, F5PL AS \""F5 P/L\"",F5PC AS \""F5 %\"", F5TC AS \""F5 COUNT\"" 
, F6PL AS \""F6 P/L\"",F6PC AS \""F6 %\"", F6TC AS \""F6 COUNT\"" 
,F7PL AS \""F7 P/L\"", F7PC AS \""F7 %\"", F7TC AS \""F7 COUNT\""  FROM TBL_TRADEBOARD ORDER BY ID ASC "; SQL statement:
SELECT concat(FEEDSECID,'-',TSCRIB,'-',TRADESECID) as SCRIB, F1PL as \"F1 P/L\",F1PC as \"F1 %\", F1TC as \"F1 COUNT\" , F2PL as \"F2 P/L\",F2PC as \"F2 %\", F2TC as \"F2 COUNT\"
, F3PL as \"F3 P/L\",F3PC as \"F3 %\", F3TC as \"F3 COUNT\" 
, F4PL as \"F4 P/L\",F4PC as \"F4 %\", F4TC as \"F4 COUNT\" 
, F5PL as \"F5 P/L\",F5PC as \"F5 %\", F5TC as \"F5 COUNT\" 
, F6PL as \"F6 P/L\",F6PC as \"F6 %\", F6TC as \"F6 COUNT\" 
,F7PL as \"F7 P/L\", F7PC as \"F7 %\", F7TC as \"F7 COUNT\"  from TBL_TRADEBOARD order by ID ASC [42000-175]
05-08 09:44:15 jdbc[39]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT * FROM TBL_FORMULA 

delete from TBL_FORMULA  where feedid=[*]'383822"; SQL statement:
SELECT * FROM TBL_FORMULA 

delete from TBL_FORMULA  where feedid='383822 [42000-175]
05-08 09:44:18 jdbc[39]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "delete from TBL_FORMULA  where feedid=[*]'383822"; SQL statement:
delete from TBL_FORMULA  where feedid='383822 [42000-175]
05-08 09:44:28 jdbc[39]: exception
org.h2.jdbc.JdbcSQLException: Column "FEEDID" not found; SQL statement:
delete from TBL_FORMULA  where feedid='38382' [42122-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:144)
	at org.h2.expression.Comparison.optimize(Comparison.java:177)
	at org.h2.command.dml.Delete.prepare(Delete.java:128)
	at org.h2.command.Parser.prepareCommand(Parser.java:240)
	at org.h2.engine.Session.prepareLocal(Session.java:436)
	at org.h2.engine.Session.prepareCommand(Session.java:379)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:168)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:156)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1321)
	at org.h2.server.web.WebApp.query(WebApp.java:1010)
	at org.h2.server.web.WebApp$1.next(WebApp.java:972)
	at org.h2.server.web.WebApp$1.next(WebApp.java:959)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
05-08 09:44:37 jdbc[39]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT * FROM TBL_FORMULA 

DELETE FROM[*] TBL_FORMULA  WHERE FEEDSECID='38382' "; SQL statement:
SELECT * FROM TBL_FORMULA 

delete from TBL_FORMULA  where feedsecid='38382' [42000-175]
05-08 09:58:04 jdbc[77]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.test(WebApp.java:845)
	at org.h2.server.web.WebApp.process(WebApp.java:219)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 14 more
05-08 09:59:58 jdbc[39]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "UPDATE TBL_FORMULA SET T2='13:00:00' , T3=NULL T4[*]='13:15:00', T1='10:05:00' WHERE ID >0

SELECT * FROM TBL_F1_HRUN_TRADES "; SQL statement:
update tbl_formula set t2='13:00:00' , t3=null t4='13:15:00', t1='10:05:00' where id >0

SELECT * FROM TBL_F1_HRUN_TRADES [42000-175]
05-08 10:00:02 jdbc[39]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "UPDATE TBL_FORMULA SET T2='13:00:00' , T3=NULL T4[*]='13:15:00', T1='10:05:00' WHERE ID >0

SELECT * FROM TBL_F1_HRUN_TRADES "; SQL statement:
update tbl_formula set t2='13:00:00' , t3=null t4='13:15:00', t1='10:05:00' where id >0

SELECT * FROM TBL_F1_HRUN_TRADES [42000-175]
05-08 10:00:03 jdbc[39]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "UPDATE TBL_FORMULA SET T2='13:00:00' , T3=NULL T4[*]='13:15:00', T1='10:05:00' WHERE ID >0 "; SQL statement:
update tbl_formula set t2='13:00:00' , t3=null t4='13:15:00', t1='10:05:00' where id >0 [42000-175]
05-08 22:33:42 jdbc[127]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT FEEDSECID AS HEAD-[*]ID,TRADESECID AS PLAYER-ID,SYMBOL,EXCHANGE,INSTTYPE,LOTSIZE,TICKSIZE,EXPIRYDD,EXPIRYMMMYY,OPTTYPE,STRIKEPRICE FROM TBL_TRADERS "; SQL statement:
SELECT FEEDSECID as HEAD-ID,TRADESECID as PLAYER-ID,SYMBOL,EXCHANGE,INSTTYPE,LOTSIZE,TICKSIZE,EXPIRYDD,EXPIRYMMMYY,OPTTYPE,STRIKEPRICE FROM TBL_TRADERS [42000-175]
05-09 00:36:39 jdbc[182]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 14 more
05-09 00:36:39 jdbc[182]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 14 more
05-09 00:42:04 jdbc[182]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT * FROM TBL_FORMULA where feeDSECID ='50395'[*]';"; SQL statement:
SELECT * FROM TBL_FORMULA where feeDSECID ='50395''; [42000-175]
05-09 01:11:25 jdbc[182]: exception
org.h2.jdbc.JdbcSQLException: Column "FEEDSCID" not found; SQL statement:
UPDATE TBL_FORMULA SET TRADESECID = '4963' WHERE FEEDSCID = ' ' AND TRADESECID = '4963' [42122-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:144)
	at org.h2.expression.Comparison.optimize(Comparison.java:177)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:131)
	at org.h2.command.dml.Update.prepare(Update.java:180)
	at org.h2.command.Parser.prepareCommand(Parser.java:240)
	at org.h2.engine.Session.prepareLocal(Session.java:436)
	at org.h2.engine.Session.prepareCommand(Session.java:379)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:168)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:156)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1321)
	at org.h2.server.web.WebApp.query(WebApp.java:1010)
	at org.h2.server.web.WebApp$1.next(WebApp.java:972)
	at org.h2.server.web.WebApp$1.next(WebApp.java:959)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
05-09 01:11:54 jdbc[182]: exception
org.h2.jdbc.JdbcSQLException: Column "FEEDSCID" not found; SQL statement:
UPDATE TBL_FORMULA SET TRADESECID = '4963'  WHERE FEEDSCID = '4963 ' AND TRADESECID = '4963' [42122-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:144)
	at org.h2.expression.Comparison.optimize(Comparison.java:177)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:131)
	at org.h2.command.dml.Update.prepare(Update.java:180)
	at org.h2.command.Parser.prepareCommand(Parser.java:240)
	at org.h2.engine.Session.prepareLocal(Session.java:436)
	at org.h2.engine.Session.prepareCommand(Session.java:379)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:168)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:156)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1321)
	at org.h2.server.web.WebApp.query(WebApp.java:1010)
	at org.h2.server.web.WebApp$1.next(WebApp.java:972)
	at org.h2.server.web.WebApp$1.next(WebApp.java:959)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
05-09 11:16:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "11:18:00" not found; SQL statement:
update tbl_formula set t1="11:18:00" where id >0 [42122-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:144)
	at org.h2.command.dml.Update.prepare(Update.java:187)
	at org.h2.command.Parser.prepareCommand(Parser.java:240)
	at org.h2.engine.Session.prepareLocal(Session.java:436)
	at org.h2.engine.Session.prepareCommand(Session.java:379)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:168)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:156)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1321)
	at org.h2.server.web.WebApp.query(WebApp.java:1010)
	at org.h2.server.web.WebApp$1.next(WebApp.java:972)
	at org.h2.server.web.WebApp$1.next(WebApp.java:959)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
05-09 12:31:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "UPDATE TBL_FORMULA SET T1='12:33:00' WHERE ID >0

SELECT[*] * FROM TBL_FORMULA "; SQL statement:
update tbl_formula set t1='12:33:00' where id >0

SELECT * FROM TBL_FORMULA [42000-175]
2018-05-16 11:05:32 database: wrong user or password; user: "ADMIN"
org.h2.message.DbException: Wrong user name or password [28000-196]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:104)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:148)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 9 more
2018-05-16 11:05:37 database: wrong user or password; user: "ADMIN"
org.h2.message.DbException: Wrong user name or password [28000-196]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:104)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:148)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 9 more
2018-05-17 14:05:59 database: wrong user or password; user: "ADMIN"
org.h2.message.DbException: Wrong user name or password [28000-196]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:104)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:148)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 9 more
05-17 14:14:58 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT * TBL_FORMULA"; SQL statement:
SELECT * TBL_FORMULA [42000-175]
05-17 14:38:37 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "UPDATE TBL_FORMULA  SET T1 ='14:39:00' WHERE ID >0

SELECT[*] * FROM TBL_F1_HRUN_TRADES "; SQL statement:
update tbl_formula  set t1 ='14:39:00' where id >0

SELECT * FROM TBL_F1_HRUN_TRADES [42000-175]
05-18 10:45:59 jdbc[9299]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "UPDATE TBL_FORMULA SET ISEND=FALSE WHERE FEEDID ='4963'

SELECT[*] * FROM TBL_FORMULA "; SQL statement:
update tbl_formula set isend=false where feedid ='4963'

SELECT * FROM TBL_FORMULA [42000-175]
05-18 10:46:03 jdbc[9299]: exception
org.h2.jdbc.JdbcSQLException: Column "FEEDID" not found; SQL statement:
update tbl_formula set isend=false where feedid ='4963' [42122-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:144)
	at org.h2.expression.Comparison.optimize(Comparison.java:177)
	at org.h2.command.dml.Update.prepare(Update.java:180)
	at org.h2.command.Parser.prepareCommand(Parser.java:240)
	at org.h2.engine.Session.prepareLocal(Session.java:436)
	at org.h2.engine.Session.prepareCommand(Session.java:379)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:168)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:156)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1321)
	at org.h2.server.web.WebApp.query(WebApp.java:1010)
	at org.h2.server.web.WebApp$1.next(WebApp.java:972)
	at org.h2.server.web.WebApp$1.next(WebApp.java:959)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
05-18 13:10:36 jdbc[9299]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT MAX(ID) FROM TBL_F2_HCAPTURE_TRADES FEEDSECID=[*]'14732' AND TRADESECID='14732' "; SQL statement:
SELECT MAX(id) FROM TBL_F2_HCAPTURE_TRADES FEEDSECID='14732' and TRADESECID='14732' [42000-175]
05-18 13:12:10 jdbc[9299]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT MAX(ID) FROM TBL_F2_HCAPTURE_TRADES FEEDSECID=[*]'14732' AND TRADESECID='14732' "; SQL statement:
SELECT MAX(id) FROM TBL_F2_HCAPTURE_TRADES FEEDSECID='14732' and TRADESECID='14732' [42000-175]
05-21 09:45:59 jdbc[55]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 14 more
05-21 10:00:54 jdbc[55]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT * FROM TBL_F1_HRUN_TRADES WHERE ID = (SELECT MAX(ID) FROM TBL_F1_HRUN_TRADES WHERE FEEDSECID='4963' AND TRADESECID='4963') FEEDSECID[*]='4963' AND TRADESECID='4963' AND ISBUYSELLDONE='false' "; SQL statement:
SELECT * FROM TBL_F1_HRUN_TRADES where id = (SELECT MAX(id) FROM TBL_F1_HRUN_TRADES WHERE FEEDSECID='4963' and TRADESECID='4963') FEEDSECID='4963' and TRADESECID='4963' and ISBUYSELLDONE='false' [42000-175]
05-21 10:00:58 jdbc[55]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT * FROM TBL_F1_HRUN_TRADES WHERE ID = (SELECT MAX(ID) FROM TBL_F1_HRUN_TRADES WHERE FEEDSECID='4963' AND TRADESECID='4963') FEEDSECID[*]='4963' AND TRADESECID='4963' AND ISBUYSELLDONE='false' "; SQL statement:
SELECT * FROM TBL_F1_HRUN_TRADES where id = (SELECT MAX(id) FROM TBL_F1_HRUN_TRADES WHERE FEEDSECID='4963' and TRADESECID='4963') FEEDSECID='4963' and TRADESECID='4963' and ISBUYSELLDONE='false' [42000-175]
05-21 12:22:41 jdbc[55]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT * FROM TBL_F1_HRUN_TRADES where id = (SELECT MAX(id) FROM TBL_F1_HRUN_TRADES WHERE FEEDSECID='14732' and TRADESECID='14732' ) and FEEDSECID='14732'  and TRADESECID='14732'  and ISBUYSELLDONE='false'[*]"""; SQL statement:
SELECT * FROM TBL_F1_HRUN_TRADES where id = (SELECT MAX(id) FROM TBL_F1_HRUN_TRADES WHERE FEEDSECID='14732' and TRADESECID='14732' ) and FEEDSECID='14732'  and TRADESECID='14732'  and ISBUYSELLDONE='false'" [42000-175]
05-21 12:36:39 jdbc[55]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "PDATE[*] TBL_FORMULA  SET T1='12:38:00' , T2 ='13:38:00' , T4='13:45:00' WHERE ID >1 "; expected "PREPARE, {"; SQL statement:
pdate tbl_formula  set t1='12:38:00' , t2 ='13:38:00' , t4='13:45:00' where id >1 [42001-175]
